# Generated by Django 5.0.4 on 2024-08-05 09:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0006_post_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="post",
            name="sub_headline",
        ),
    ]
