# Generated by Django 5.0.4 on 2024-08-05 09:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0007_remove_post_slug_remove_post_sub_headline"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(blank=True, null=True),
        ),
    ]
